Update BOM and metrics plugin to fix test warnings on jdk11
This removes

1) Error injecting constructor,
   java.lang.reflect.InaccessibleObjectException: Unable to make public
   long
   com.sun.management.internal.OperatingSystemImpl.getProcessCpuTime()
   accessible: module jdk.management does not "opens
   com.sun.management.internal" to unnamed module @7fd4acee
     at
     jenkins.metrics.impl.VMMetricProviderImpl.<init>(VMMetricProviderImpl.java:56)

as recent metrics plugin doesn't rely on this private method as of
https://github.com/jenkinsci/metrics-plugin/pull/42